### PR TITLE
Set up source builds with CMakeWrapper.jl

### LINKED ISSUE #42: Supporting non-Ubuntu Linux OS
What is the long term plan for supporting Linux OS like ArchLinux or Fedora ? Having prebuilt binaries for them or using a fallback that downloads director and build it from source ?

### PR DESCRIPTION
**Pull request by rdeits**
Fixes #42

### CODE REVIEW

**Comment by rdeits** [comment]
@blegat this is pretty close to working, pending https://github.com/RobotLocomotion/director/pull/484 and https://github.com/JuliaLang/METADATA.jl/pull/8199

**Comment by blegat** [comment]
@rdeits Thanks a lot ! Why is it pending the release if CDDLib v0.1.3 ?

**Comment by rdeits** [comment]
I think CDDLib v0.1.2 is incompatible with Polyhedra v0.1.4 (see the Travis build errors on this branch for reference). I *could* tag a maximum upper bound on cddlib.jl and polyhedra.jl, but I'd rather just wait for cddlib v0.1.3 and set new lower bounds instead.

**Comment by blegat** [comment]
Yes, it is indeed incompatible. I said that because I didn't see it on your REQUIRE since I forgot to check `test/REQUIRE` :)

**Pull request merged**
