### PR TITLE
Add `script` keyword argument to `new_window`

### PR DESCRIPTION
**Pull request by tkoolen**

### CODE REVIEW

**Comment by rdeits** [comment]
looks good, thanks!

**Comment by tkoolen** [comment]
So on my local machine I had to play around with the `sleep` time a bit to get it to pass. Should I use `wait(filedescriptor)` instead, or is this just not going to work when the visualizer is run headless?

**Comment by rdeits** [comment]
We'd have to turn on xvfb on Travis to get this working, otherwise Director exits immediately. I can take a look tomorrow

**Comment by tkoolen** [comment]
I improved the test a bit; the script now sends an LCM message that the test code listens for. It also uses `timedwait` instead of `sleep`ing for a fixed amount of time.

**Comment by tkoolen** [comment]
Ugh, I still can't tell if the visualizer is actually getting started on Linux. There seem to be no errors and the `drake-visualizer: cannot connect to X server` message is gone, but then the test doesn't pass. Any ideas? I'm also having trouble testing with xvfb locally (where I do get an error, possibly due to an older VTK version).

I just noticed that before I made these changes, the test actually passed on OSX. Would running the script test set only on OSX be good enough?

**Comment by rdeits** [comment]
Yeah, running it on osx only is totally fine

**Comment by tkoolen** [comment]
OK. For future reference, this is as far as I got with xvfb: https://github.com/tkoolen/DrakeVisualizer.jl/tree/script-xvfb.

I also decided to get rid of the LCM stuff again just to simplify the test. I'm still using `timedwait`, so it should run quickly.

**Pull request closed without merging**
