### PR TITLE
Use LCMCore.LCMType for CommsT.

### PR DESCRIPTION
**Pull request by tkoolen**
Just to clean things up a bit.

### CODE REVIEW

**Comment by rdeits** [comment]
This is great, thanks!

**Comment by tkoolen** [comment]
Requires https://github.com/JuliaLang/METADATA.jl/pull/13013.

**Comment by rdeits** [comment]
Ok, that's merged, so I've restarted the Travis builds

**Comment by rdeits** [comment]
Travis mac builds seem to no longer have `pip` available. Weird.

**Comment by rdeits** [comment]
Ah: https://github.com/travis-ci/travis-ci/issues/8829#issuecomment-348735335

**Comment by rdeits** [comment]
I'll resolve the mac issues in #68

**Pull request merged**
