### PR TITLE
Add `script` keyword argument to `new_window (was: 'Try again with xvfb')

### PR DESCRIPTION
**Pull request by tkoolen**

### CODE REVIEW

**Comment by tkoolen** [comment]
Working now on Linux! xvfb was working all along, there were just missing Python dependencies that caused the script to not run. For future reference: there is no stdout output from the drake-visualizer process in the Travis log.

Just doing some final touchups.

Ref #62 for discussion.

**Comment by rdeits** [comment]
Hooray! Thanks for figuring that out.

**Comment by tkoolen** [comment]
I'm trying to get things to work on OSX as well. I think I'm close.

**Comment by rdeits** [comment]
Ok, that would be awesome but is definitely not necessary 🙂

**Comment by tkoolen** [comment]
Decided to give up on running the `script` test set on OSX for now. I feel like I'm 99% of the way there (process is definitely running, I think all of the dependencies are installed correctly), but it's still not working and I'm out of ideas right now. I think the changes to the .travis.yml are still valuable though, so I'll leave those in.

**Comment by tkoolen** [comment]
OK, all set.

**Pull request merged**
